           
<RightContentCls>
    disabled: True
    adaptive_size: True
    pos_hint: {"center_y": .5}

    MDIconButton:
        icon: root.icon
        user_font_size: "16sp"
        md_bg_color_disabled: 0, 0, 0, 0

    MDLabel:
        text: root.text
        font_style: "Caption"
        adaptive_size: True
        pos_hint: {"center_y": .5}


<Item>
    IconLeftWidget:
        icon: root.left_icon

    RightContentCls:
        id: container
        icon: root.right_icon
        text: root.right_text

# ScreenManager:
#     MainMenu:
#     GasMenu:
#     WaterMenu:
#     GasMenuH2Gas:
    
    
<GasMenu>:
    name: 'gas'
    BoxLayout:
        orientation: 'vertical'

    MDNavigationLayout:

        ScreenManager:

            Screen:

                BoxLayout:
                    orientation: 'vertical'

                    MDTopAppBar:
                        title: "GAS"
                        elevation: 4
                        pos_hint: {"top": 1}
                        md_bg_color: "#ffa500"
                        specific_text_color: "#4a4939"
                        left_action_items: [['arrow-left', lambda x: root.change_screen('menu')]]
                        right_action_items: [["dots-vertical", lambda x: app.callback(x)]]
                           
                       

                    MDBottomNavigation:
                        selected_color_background: "orange"
                        text_color_active: "lightgrey"
            
                        MDBottomNavigationItem:
                            name: 'gas1'
                            text: 'H2 GAS'
                            icon: 'fire-circle'
                            
                            GridLayout:
                                cols: 2
                                padding: dp(16)
                                spacing: dp(10)

                                MDTextField:
                                    id: tech_shift
                                    hint_text: 'Click me to show shift'
                                    mode: "rectangle"
                                    on_focus: app.show_drop_down(self, self.focus)

                                MDTextField:
                                    hint_text: "Tech No."
                                    id: emp_no
                                    mode: "rectangle"

                                MDTextField:
                                    id: date_time_encode_h2_gas
                                    hint_text: "Date/Time Encode"
                                    mode: "rectangle"
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    readonly: True
                                    on_focus: if self.focus: app.show_datetime_picker()

                                MDTextField:
                                    hint_text: "Temperature"
                                    id: temp
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Nitrogen"
                                    id: n_pressure
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Pressure"
                                    id: p_pressure
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Nit cyl pressure reading"
                                    id: n_cylinder_pressure
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Pri Pressure gauge BH2"
                                    id: p_pressure_gauge_bhs2
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Pri Pressure gauge Pallet"
                                    id: p_pressure_gauge_pallet
                                    mode: "rectangle"

                                MDTextField:
                                    hint_text: "Remarks"
                                    id: remarks
                                    mode: "rectangle"
                                    multiline: True

                                MDTextField:
                                    hint_text: "Seco Pressure gauge BH2"
                                    id: s_pressure_gauge
                                    mode: "rectangle"

                                    
                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: None
                                height: self.minimum_height
                                spacing: dp(10)
                                padding: dp(16)  # Add padding here

                                Widget:  # Spacer to push the button to the right
                                
                                MDRaisedButton:
                                    text: "Save"
                                    size_hint: None, None
                                    size: "340dp", "90dp"
                                    on_press: app.insert_to_database_h2_gas()  # Replace with your button press function          

                        MDBottomNavigationItem:
                            name: 'gas2'
                            text: 'N2(Liquid)'
                            icon: 'cup-water'

                            GridLayout:
                                cols: 2
                                padding: dp(16)
                                spacing: dp(10)

                                MDTextField:
                                    hint_text: "Shift"
                                    id: shift_n2
                                    mode: "rectangle"
                                    on_focus: app.show_drop_down(self, self.focus)

                                MDTextField:
                                    id: tech_no
                                    hint_text: "Tech No."
                                    mode: "rectangle"

                                MDTextField:
                                    id: date_time_encode_n2_gas
                                    hint_text: "Date/Time Encode"
                                    mode: "rectangle"
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    readonly: True
                                    on_focus: if self.focus: app.show_datetime_picker()

                                MDTextField:
                                    id: n2_level_mm_of_h2o
                                    hint_text: "N2 LEVEL mm of H2O"
                                    mode: "rectangle"

                                MDTextField:
                                    id: inventory_m3
                                    hint_text: "INVENTORY in mÂ³"
                                    mode: "rectangle"

                                MDTextField:
                                    id: pressure_psi
                                    hint_text: "PRESSURE in PSI (160 max)"
                                    mode: "rectangle"

                                MDTextField:
                                    id: volume_percentage
                                    hint_text: "% Volume"
                                    mode: "rectangle"

                                MDTextField:
                                    id: ppm
                                    hint_text: "PPM"
                                    mode: "rectangle"

                                MDTextField:
                                    id: vaporizer_use_no_1_no_2
                                    hint_text: "Vaporizer Use No.1 / No.2"
                                    mode: "rectangle"

                                MDTextField:
                                    id: remarks
                                    hint_text: "Remarks"
                                    mode: "rectangle"

                                    
                            BoxLayout:
                                orientation: 'horizontal'
                                size_hint_y: None
                                height: self.minimum_height
                                spacing: dp(10)
                                padding: dp(16)  # Add padding here

                                Widget:  # Spacer to push the button to the right
                                
                                MDRaisedButton:
                                    text: "Save"
                                    size_hint: None, None
                                    size: "340dp", "90dp"
                                    on_press: app.insert_to_database_n2_liquid()  # Replace with your button press function      